"""
Payment manager for the Tomato Logistics Platform.

The payment manager runs after reservation and before notification. It creates
simple payment records and asks a payment gateway to initialize the payment.
No database queries, real payment links, or external API calls are made here.
"""

import logging
import uuid
from datetime import datetime

try:
    from gateways.flutterwave import FlutterwaveGateway
    from logger import EngineLogger
except ImportError:
    from engine.gateways.flutterwave import FlutterwaveGateway
    from engine.logger import EngineLogger


class PaymentError(ValueError):
    """Raised when payment data is missing or invalid."""


class PaymentStatus:
    """Stores the payment statuses supported by the engine."""

    PENDING = "PENDING"
    PAID = "PAID"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"


class PaymentManager:
    """
    Controls the payment process after reservation and before notification.

    The manager prepares payment dictionaries that match the database contract
    and are ready for a future Flutterwave integration. It does not generate
    database IDs and does not make network requests.
    """

    def __init__(
        self,
        gateway=None,
        logger=None,
        transport_rate_per_kg=2.0,
        storage_rate_per_kg=1.0,
        currency="RWF",
    ):
        """
        Create a payment manager.

        Receives an optional gateway, logger, rates, and currency. Returns a
        manager that can prepare, initialize, verify, and refund payments.
        """
        self.gateway = gateway or FlutterwaveGateway()
        self.transport_rate_per_kg = transport_rate_per_kg
        self.storage_rate_per_kg = storage_rate_per_kg
        self.currency = currency
        self.payment_counter = 0

        if logger:
            self.logger = logger
        elif EngineLogger:
            self.logger = EngineLogger()
        else:
            self.logger = logging.getLogger(__name__)

    def calculate_transport_cost(self, reservation):
        """
        Calculate transport cost for one reserved trip.

        Receives a reserved trip dictionary. Returns the transport amount.
        """
        total_load = self.get_total_load(reservation)
        return total_load * self.transport_rate_per_kg

    def calculate_storage_cost(self, reservation):
        """
        Calculate cold storage cost for one reserved trip.

        Receives a reserved trip dictionary. Returns the storage amount.
        """
        total_load = self.get_total_load(reservation)
        return total_load * self.storage_rate_per_kg

    def calculate_total_amount(self, reservation):
        """
        Calculate the full payment amount for one reserved trip.

        Receives a reserved trip dictionary. Returns transport plus storage.
        """
        transport_cost = self.calculate_transport_cost(reservation)
        storage_cost = self.calculate_storage_cost(reservation)
        return transport_cost + storage_cost

    def create_payment(self, reservation):
        """
        Create a local payment record for one reserved trip.

        Receives one reserved trip dictionary and returns one trip-level payment.
        Farmer split details are included only as context for future versions.
        """
        self.validate_reservation(reservation)
        self.payment_counter += 1

        payment_reference = self.generate_payment_reference(reservation)
        farmer_payment_context = self.get_farmer_payment_context(reservation)
        payer_phone = self.get_payer_phone(reservation)
        payee_phone = self.get_payee_phone(reservation)
        created_at = datetime.now()

        return {
            # payment_id is generated by PostgreSQL after insertion.
            "payment_id": reservation.get("payment_id"),
            "allocation_id": self.get_allocation_id(reservation),
            "farmer_id": reservation.get("farmer_id"),
            "payer_type": "FARMER",
            "payee_type": "PLATFORM",
            "payer_phone": payer_phone,
            "payee_phone": payee_phone,
            "amount": self.calculate_total_amount(reservation),
            "currency": self.currency,
            "purpose": "TRIP_TRANSPORT_AND_STORAGE",
            "payment_method": "FLUTTERWAVE",
            "payment_status": PaymentStatus.PENDING,
            "status": PaymentStatus.PENDING,
            "payment_reference": payment_reference,
            "flutterwave_ref": payment_reference,
            "tx_ref": payment_reference,
            "payment_link": None,
            "created_at": created_at,
            "paid_at": None,
            "settled_at": None,
            "database_generated_id_pending": True,
            "payment_scope": "TRIP",
            "split_payments_enabled": False,
            "farmer_payment_context": farmer_payment_context,
            "farmer_count": len(farmer_payment_context),
        }

    def initialize_payment(self, reservation_results):
        """
        Create and initialize payments for all reserved trips.

        Receives reservation results and returns the same structure enriched
        with one mocked Flutterwave payment per trip. A real Flutterwave HTTP
        call belongs inside the gateway, not inside this manager.
        """
        self.logger.info("Payment process started.")

        trip_allocations = reservation_results.get("trip_allocations", [])
        payments = []
        enriched_trips = []

        for trip in trip_allocations:
            payment = self.create_payment(trip)
            gateway_response = self.gateway.initialize_payment(payment)

            if gateway_response.get("status") == "success":
                payment["payment_link"] = gateway_response.get("payment_link")
                payment["flutterwave_ref"] = gateway_response.get(
                    "tx_ref",
                    payment["flutterwave_ref"]
                )
                payment["tx_ref"] = payment["flutterwave_ref"]
            else:
                self.update_payment_status(payment, PaymentStatus.FAILED)

            payments.append(payment)
            enriched_trips.append(self.add_payment_summary_to_trip(trip, payment))

        payment_results = reservation_results.copy()
        payment_results["trip_allocations"] = enriched_trips
        payment_results["payments"] = payments
        payment_results["payment_status"] = PaymentStatus.PENDING
        payment_results["total_payments"] = len(payments)

        self.logger.info(f"{len(payments)} payments initialized.")
        self.logger.info("Payment process completed.")
        return payment_results

    def verify_payment(self, payment):
        """
        Verify one payment using the configured gateway.

        Receives one payment dictionary. Returns it with an updated status. The
        current gateway is mocked; real Flutterwave verification will be added
        in the gateway implementation.
        """
        tx_ref = payment.get("flutterwave_ref") or payment.get("tx_ref")
        if not tx_ref:
            raise PaymentError("Payment transaction reference is missing.")

        response = self.gateway.verify_payment(tx_ref)
        new_status = response.get("payment_status", PaymentStatus.PENDING)
        return self.update_payment_status(payment, new_status)

    def refund_payment(self, payment):
        """
        Request a refund for one payment using the configured gateway.

        Receives one payment dictionary. Returns it with refund status. Real
        Flutterwave refund requests should be implemented inside the gateway.
        """
        tx_ref = payment.get("flutterwave_ref") or payment.get("tx_ref")
        if not tx_ref:
            raise PaymentError("Payment transaction reference is missing.")

        response = self.gateway.refund_payment(tx_ref)
        new_status = response.get("payment_status", PaymentStatus.REFUNDED)
        return self.update_payment_status(payment, new_status)

    def update_payment_status(self, payment, status):
        """
        Change the status of one payment record.

        Receives a payment dictionary and a supported status. Returns the same
        payment with both database and backward-compatible status fields.
        """
        allowed_statuses = {
            PaymentStatus.PENDING,
            PaymentStatus.PAID,
            PaymentStatus.FAILED,
            PaymentStatus.REFUNDED,
        }

        if status not in allowed_statuses:
            raise PaymentError("Unsupported payment status.")

        payment["payment_status"] = status
        payment["status"] = status

        if status == PaymentStatus.PAID:
            paid_at = datetime.now()
            payment["paid_at"] = paid_at
            payment["settled_at"] = paid_at
        return payment

    def add_payment_summary_to_trip(self, trip, payment):
        """
        Add simple payment details to a reserved trip.

        Receives a trip and payment record, then returns a copied trip enriched
        with payment fields for notification and future persistence.
        """
        enriched_trip = trip.copy()
        enriched_trip["payment_id"] = payment["payment_id"]
        enriched_trip["payment_status"] = payment["payment_status"]
        enriched_trip["payment_amount"] = payment["amount"]
        enriched_trip["payment_reference"] = payment["payment_reference"]
        enriched_trip["flutterwave_ref"] = payment["flutterwave_ref"]
        enriched_trip["payment_link"] = payment["payment_link"]
        enriched_trip["payment_scope"] = payment["payment_scope"]
        enriched_trip["split_payments_enabled"] = payment[
            "split_payments_enabled"
        ]
        enriched_trip["farmer_payment_context"] = payment[
            "farmer_payment_context"
        ]
        return enriched_trip

    def get_farmer_payment_context(self, reservation):
        """
        Collect farmer details for future payment splitting.

        Receives one reserved trip and returns a list of farmer payment context
        dictionaries. It does not split the payment amount.
        """
        forecasts = reservation.get("forecasts", [])

        if not forecasts and reservation.get("cluster"):
            forecasts = reservation["cluster"].get("forecasts", [])

        farmer_context = []
        for forecast in forecasts:
            farmer_context.append({
                "farmer_id": forecast.get("farmer_id"),
                "forecast_id": forecast.get("forecast_id"),
                "quantity_kg": forecast.get("quantity_kg"),
                "payment_split_status": "NOT_SPLIT",
            })

        return farmer_context

    def generate_payment_reference(self, reservation=None):
        """
        Generate a unique payment reference for Flutterwave.

        Receives an optional reservation dictionary. Returns a reference that is
        independent from the database payment_id and suitable for tx_ref later.
        """
        reservation = reservation or {}
        allocation_part = reservation.get("allocation_id")
        if not allocation_part:
            allocation_part = reservation.get("temporary_trip_key", "PENDING")

        unique_part = uuid.uuid4().hex[:12].upper()
        return f"TLP-{allocation_part}-{unique_part}"

    def get_allocation_id(self, reservation):
        """
        Get the allocation ID used by the payment record.

        Receives a reserved trip dictionary. Returns the database allocation_id
        when available, otherwise None because PostgreSQL must generate it.
        """
        allocation_id = reservation.get("allocation_id")
        if allocation_id:
            return allocation_id

        return None

    def get_total_load(self, reservation):
        """
        Read and validate the total load for one reserved trip.

        Receives a reserved trip dictionary. Returns total_load_kg as a float.
        """
        total_load = reservation.get("total_load_kg")

        if total_load is None:
            raise PaymentError("Total load is missing.")

        try:
            total_load = float(total_load)
        except (TypeError, ValueError) as error:
            raise PaymentError("Total load must be a number.") from error

        if total_load <= 0:
            raise PaymentError("Total load must be greater than 0 kg.")

        return total_load

    def validate_reservation(self, reservation):
        """
        Check that a reserved trip has the data needed for payment.

        Receives a reserved trip dictionary. Returns None or raises PaymentError
        if the trip is missing required payment data.
        """
        if reservation.get("status") != "RESERVED":
            raise PaymentError("Payments can only be created for reserved trips.")

        if not reservation.get("truck_id"):
            raise PaymentError("Truck ID is missing.")

        if not reservation.get("hub_id"):
            raise PaymentError("Hub ID is missing.")

        self.get_total_load(reservation)

    def get_payer_phone(self, reservation):
        """
        Get the farmer phone number for a payment.

        Receives a reserved trip dictionary. Returns the first farmer phone when
        available, otherwise None for the service layer to complete later.
        """
        farmer_phones = reservation.get("farmer_phones") or []
        if farmer_phones:
            return farmer_phones[0]
        return reservation.get("farmer_phone")

    def get_payee_phone(self, reservation):
        """
        Get the payment receiver phone number.

        Receives a reserved trip dictionary. Returns admin_phone as the current
        platform payee contact, falling back to hub_phone during demos.
        """
        return reservation.get("admin_phone") or reservation.get("hub_phone")
