
-- The Schema file builds the database tables for our Cold-chain system.
-- The tables are made in an order that lets links between them work.
-------------------------------------------------------------

-- Remove old tables first, starting with the tables that depend on others.
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS excluded_trips CASCADE;
DROP TABLE IF EXISTS trip_allocations CASCADE;
DROP TABLE IF EXISTS coordination_plans CASCADE;
DROP TABLE IF EXISTS harvest_forecasts CASCADE;
DROP TABLE IF EXISTS trucks CASCADE;
DROP TABLE IF EXISTS cold_hubs CASCADE;
DROP TABLE IF EXISTS transporters CASCADE;
DROP TABLE IF EXISTS farmers CASCADE;
DROP TABLE IF EXISTS sectors CASCADE;
DROP TABLE IF EXISTS users CASCADE;


-- This table keeps login accounts for farmers, transporters, and admins.
-- Passwords are saved in a protected form, not as plain words.

CREATE TABLE users (
    user_id       INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)   NOT NULL UNIQUE,
    password_hash VARCHAR(255)  NOT NULL,
    role          VARCHAR(20)   NOT NULL,              
    is_active     BOOLEAN       NOT NULL DEFAULT TRUE,
    last_login    TIMESTAMP     NULL,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- This table keeps sectors, which are administrative areas that group farmers and transporters.

CREATE TABLE sectors (
    sector_id INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(50)  NOT NULL,
    district  VARCHAR(50)  NOT NULL,
    cell      VARCHAR(50)  NULL,
    village   VARCHAR(50)  NULL
);


-- This table keeps farmer details and connects each farmer to a login account.

CREATE TABLE farmers (
    farmer_id INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   INT           NOT NULL,
    sector_id INT           NOT NULL,
    name      VARCHAR(100)  NOT NULL,
    phone     VARCHAR(10)   NOT NULL,
    cell      VARCHAR(50)   NULL,
    village   VARCHAR(50)   NULL,
    CONSTRAINT fk_farmers_user
        FOREIGN KEY (user_id)   REFERENCES users(user_id)     ON DELETE CASCADE,
    CONSTRAINT fk_farmers_sector
        FOREIGN KEY (sector_id) REFERENCES sectors(sector_id) ON DELETE RESTRICT
);


-- This table keeps transporter details and connects each transporter to a login account.

CREATE TABLE transporters (
    transporter_id INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        INT          NOT NULL,
    sector_id      INT          NOT NULL,
    name           VARCHAR(50)  NOT NULL,
    phone          VARCHAR(50)  NOT NULL,
    CONSTRAINT fk_transporters_user
        FOREIGN KEY (user_id)   REFERENCES users(user_id)     ON DELETE CASCADE,
    CONSTRAINT fk_transporters_sector
        FOREIGN KEY (sector_id) REFERENCES sectors(sector_id) ON DELETE RESTRICT
);


-- This table keeps cold hubs that are used to store harvest from farmers.

CREATE TABLE cold_hubs (
    hub_id                INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sector_id             INT          NOT NULL,
    name                  VARCHAR(50)  NOT NULL,
    phone                 VARCHAR(15)  NULL,
    total_capacity_kg     REAL         NOT NULL,
    available_capacity_kg REAL         NOT NULL,
    operating_status      VARCHAR(10)  NOT NULL DEFAULT 'OPEN',  
    CONSTRAINT fk_cold_hubs_sector
        FOREIGN KEY (sector_id) REFERENCES sectors(sector_id) ON DELETE RESTRICT,
    CONSTRAINT chk_hub_capacity
        CHECK (available_capacity_kg >= 0 AND available_capacity_kg <= total_capacity_kg)
);


-- This table keeps trucks that are used to transport harvest from farmers to cold hubs.

CREATE TABLE trucks (
    truck_id       INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transporter_id INT          NOT NULL,
    plate_number   VARCHAR(15)  NOT NULL UNIQUE,
    capacity_kg    REAL         NOT NULL,
    sector_id      INT          NOT NULL,
    status         VARCHAR(10)  NOT NULL DEFAULT 'IDLE',   
    CONSTRAINT fk_trucks_transporter
        FOREIGN KEY (transporter_id) REFERENCES transporters(transporter_id) ON DELETE CASCADE,
    CONSTRAINT fk_trucks_sector
        FOREIGN KEY (sector_id)      REFERENCES sectors(sector_id)           ON DELETE RESTRICT
);

-- This table keeps track of harvest forecasts submitted by farmers.

CREATE TABLE harvest_forecasts (
    forecast_id  INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farmer_id    INT          NOT NULL,
    quantity_kg  REAL         NOT NULL,
    harvest_date TIMESTAMP    NOT NULL,
    status       VARCHAR(10)  NOT NULL DEFAULT 'PENDING',  
    submitted_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_forecasts_farmer
        FOREIGN KEY (farmer_id) REFERENCES farmers(farmer_id) ON DELETE CASCADE,
    CONSTRAINT chk_forecast_quantity
        CHECK (quantity_kg > 0)
);


-- This table keeps track of coordination plans that are generated based on forecasts.

CREATE TABLE coordination_plans (
    plan_id      INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sector_id    INT          NOT NULL,
    generated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status       VARCHAR(50)  NOT NULL DEFAULT 'DRAFT',    
    CONSTRAINT fk_plans_sector
        FOREIGN KEY (sector_id) REFERENCES sectors(sector_id) ON DELETE RESTRICT
);


-- This table keeps track of which trucks are assigned to which trips in a plan.

CREATE TABLE trip_allocations (
    allocation_id         INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id               INT          NOT NULL,
    truck_id              INT          NOT NULL,
    hub_id                INT          NOT NULL,
    sector_id             INT          NOT NULL,
    total_load_kg         REAL         NOT NULL,
    pickup_start          TIMESTAMP    NULL,
    estimated_hub_arrival TIMESTAMP    NULL,
    status                VARCHAR(10)  NOT NULL DEFAULT 'SCHEDULED', 
    CONSTRAINT fk_alloc_plan
        FOREIGN KEY (plan_id)   REFERENCES coordination_plans(plan_id) ON DELETE CASCADE,
    CONSTRAINT fk_alloc_truck
        FOREIGN KEY (truck_id)  REFERENCES trucks(truck_id)            ON DELETE RESTRICT,
    CONSTRAINT fk_alloc_hub
        FOREIGN KEY (hub_id)    REFERENCES cold_hubs(hub_id)           ON DELETE RESTRICT,
    CONSTRAINT fk_alloc_sector
        FOREIGN KEY (sector_id) REFERENCES sectors(sector_id)          ON DELETE RESTRICT,
    CONSTRAINT chk_alloc_load
        CHECK (total_load_kg > 0)
);


-- This table keeps track of trips that were excluded from the plan, along with the reason.

CREATE TABLE excluded_trips (
    exclusion_id INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forecast_id  INT          NOT NULL,
    plan_id      INT          NOT NULL,
    reason_code  VARCHAR(50)  NOT NULL,   
    excluded_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_excl_forecast
        FOREIGN KEY (forecast_id) REFERENCES harvest_forecasts(forecast_id) ON DELETE CASCADE,
    CONSTRAINT fk_excl_plan
        FOREIGN KEY (plan_id)     REFERENCES coordination_plans(plan_id)    ON DELETE CASCADE
);


-- Notifications table to keep track of messages sent to farmers and transporters.

CREATE TABLE notifications (
    notification_id INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_type  VARCHAR(50)   NOT NULL,   
    recipient_phone VARCHAR(50)   NOT NULL,
    channel         VARCHAR(50)   NOT NULL DEFAULT 'SMS',  
    message         VARCHAR(255)  NOT NULL,
    status          VARCHAR(10)   NOT NULL DEFAULT 'QUEUED', 
    sent_time       TIMESTAMP     NULL,
    related_trip_id INT           NULL,
    CONSTRAINT fk_notif_trip
        FOREIGN KEY (related_trip_id) REFERENCES trip_allocations(allocation_id) ON DELETE SET NULL
);
