
-- The Schema file builds the database tables for our Cold-chain system.
-- The tables are made in an order that lets links between them work.
-------------------------------------------------------------

-- Remove old tables first, starting with the tables that depend on others.
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS excluded_trips CASCADE;
DROP TABLE IF EXISTS trip_allocations CASCADE;
DROP TABLE IF EXISTS coordination_plans CASCADE;
DROP TABLE IF EXISTS harvest_forecasts CASCADE;
DROP TABLE IF EXISTS trucks CASCADE;
DROP TABLE IF EXISTS cold_hubs CASCADE;
DROP TABLE IF EXISTS transporters CASCADE;
DROP TABLE IF EXISTS farmers CASCADE;
DROP TABLE IF EXISTS sectors CASCADE;
DROP TABLE IF EXISTS users CASCADE;


-- This table keeps login accounts for farmers, transporters, and admins.
-- Passwords are saved in a protected form, not as plain words.

CREATE TABLE users (
    user_id       INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)   NOT NULL UNIQUE,
    password_hash VARCHAR(255)  NOT NULL,
    role          VARCHAR(20)   NOT NULL,              
    is_active     BOOLEAN       NOT NULL DEFAULT TRUE,
    last_login    TIMESTAMP     NULL,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_users_role
        CHECK (role IN ('ADMIN', 'FARMER', 'TRANSPORTER', 'HUB_OPERATOR'))
);


-- This table keeps sectors, which are administrative areas that group farmers and transporters.

CREATE TABLE sectors (
    sector_id INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(50)  NOT NULL,
    district  VARCHAR(50)  NOT NULL,
    cell      VARCHAR(50)  NULL,
    village   VARCHAR(50)  NULL
);


-- This table keeps farmer details and connects each farmer to a login account.

CREATE TABLE farmers (
    farmer_id INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   INT           NOT NULL,
    sector_id INT           NOT NULL,
    name      VARCHAR(100)  NOT NULL,
    phone     VARCHAR(15)   NOT NULL,
    cell      VARCHAR(50)   NULL,
    village   VARCHAR(50)   NULL,
    CONSTRAINT fk_farmers_user
        FOREIGN KEY (user_id)   REFERENCES users(user_id)     ON DELETE CASCADE,
    CONSTRAINT fk_farmers_sector
        FOREIGN KEY (sector_id) REFERENCES sectors(sector_id) ON DELETE RESTRICT
);


-- This table keeps transporter details and connects each transporter to a login account.

CREATE TABLE transporters (
    transporter_id INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        INT          NOT NULL,
    sector_id      INT          NOT NULL,
    name           VARCHAR(50)  NOT NULL,
    phone          VARCHAR(15)  NOT NULL,
    CONSTRAINT fk_transporters_user
        FOREIGN KEY (user_id)   REFERENCES users(user_id)     ON DELETE CASCADE,
    CONSTRAINT fk_transporters_sector
        FOREIGN KEY (sector_id) REFERENCES sectors(sector_id) ON DELETE RESTRICT
);


-- This table keeps cold hubs that are used to store harvest from farmers.

CREATE TABLE cold_hubs (
    hub_id                INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sector_id             INT          NOT NULL,
    name                  VARCHAR(50)  NOT NULL,
    phone                 VARCHAR(15)  NULL,
    total_capacity_kg     REAL         NOT NULL,
    available_capacity_kg REAL         NOT NULL,
    operating_status      VARCHAR(10)  NOT NULL DEFAULT 'OPEN',  
    CONSTRAINT fk_cold_hubs_sector
        FOREIGN KEY (sector_id) REFERENCES sectors(sector_id) ON DELETE RESTRICT,
    CONSTRAINT chk_hub_capacity
        CHECK (available_capacity_kg >= 0 AND available_capacity_kg <= total_capacity_kg),
    CONSTRAINT chk_cold_hubs_operating_status
        CHECK (operating_status IN ('OPEN', 'CLOSED'))
);


-- This table keeps trucks that are used to transport harvest from farmers to cold hubs.

CREATE TABLE trucks (
    truck_id       INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transporter_id INT          NOT NULL,
    plate_number   VARCHAR(15)  NOT NULL UNIQUE,
    capacity_kg    REAL         NOT NULL,
    sector_id      INT          NOT NULL,
    status         VARCHAR(15)  NOT NULL DEFAULT 'AVAILABLE',
    CONSTRAINT fk_trucks_transporter
        FOREIGN KEY (transporter_id) REFERENCES transporters(transporter_id) ON DELETE CASCADE,
    CONSTRAINT fk_trucks_sector
        FOREIGN KEY (sector_id)      REFERENCES sectors(sector_id)           ON DELETE RESTRICT,
    CONSTRAINT chk_trucks_status
        CHECK (status IN ('AVAILABLE', 'BUSY', 'MAINTENANCE'))
);

-- This table keeps track of harvest forecasts submitted by farmers.

CREATE TABLE harvest_forecasts (
    forecast_id  INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farmer_id    INT          NOT NULL,
    quantity_kg  REAL         NOT NULL,
    harvest_date TIMESTAMP    NOT NULL,
    status       VARCHAR(10)  NOT NULL DEFAULT 'PENDING',  
    submitted_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_forecasts_farmer
        FOREIGN KEY (farmer_id) REFERENCES farmers(farmer_id) ON DELETE CASCADE,
    CONSTRAINT chk_forecast_quantity
        CHECK (quantity_kg > 0),
    CONSTRAINT chk_harvest_forecasts_status
        CHECK (status IN ('PENDING', 'ALLOCATED', 'CANCELLED'))
);


-- This table keeps track of coordination plans that are generated based on forecasts.

CREATE TABLE coordination_plans (
    plan_id      INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sector_id    INT          NOT NULL,
    generated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status       VARCHAR(50)  NOT NULL DEFAULT 'RUNNING',
    CONSTRAINT fk_plans_sector
        FOREIGN KEY (sector_id) REFERENCES sectors(sector_id) ON DELETE RESTRICT,
    CONSTRAINT chk_coordination_plans_status
        CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED'))
);


-- This table keeps track of which trucks are assigned to which trips in a plan.

CREATE TABLE trip_allocations (
    allocation_id         INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id               INT          NOT NULL,
    truck_id              INT          NOT NULL,
    hub_id                INT          NOT NULL,
    sector_id             INT          NOT NULL,
    total_load_kg         REAL         NOT NULL,
    pickup_start          TIMESTAMP    NULL,
    estimated_hub_arrival TIMESTAMP    NULL,
    status                VARCHAR(20)  NOT NULL DEFAULT 'SCHEDULED',
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_alloc_plan
        FOREIGN KEY (plan_id)   REFERENCES coordination_plans(plan_id) ON DELETE CASCADE,
    CONSTRAINT fk_alloc_truck
        FOREIGN KEY (truck_id)  REFERENCES trucks(truck_id)            ON DELETE RESTRICT,
    CONSTRAINT fk_alloc_hub
        FOREIGN KEY (hub_id)    REFERENCES cold_hubs(hub_id)           ON DELETE RESTRICT,
    CONSTRAINT fk_alloc_sector
        FOREIGN KEY (sector_id) REFERENCES sectors(sector_id)          ON DELETE RESTRICT,
    CONSTRAINT chk_alloc_load
        CHECK (total_load_kg > 0),
    CONSTRAINT chk_trip_allocations_status
        CHECK (status IN ('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'))
);


-- This table keeps track of trips that were excluded from the plan, along with the reason.

CREATE TABLE excluded_trips (
    exclusion_id INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forecast_id  INT          NOT NULL,
    plan_id      INT          NOT NULL,
    reason_code  VARCHAR(50)  NOT NULL,
    reason_detail TEXT        NULL,
    excluded_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_excl_forecast
        FOREIGN KEY (forecast_id) REFERENCES harvest_forecasts(forecast_id) ON DELETE CASCADE,
    CONSTRAINT fk_excl_plan
        FOREIGN KEY (plan_id)     REFERENCES coordination_plans(plan_id)    ON DELETE CASCADE
);

-- This table keeps track of how much of each forecast is allocated to each trip.
CREATE TABLE forecast_allocations (

    allocation_id INT NOT NULL,

    forecast_id INT NOT NULL,

    allocated_quantity_kg REAL NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (allocation_id, forecast_id),

    FOREIGN KEY (allocation_id)
        REFERENCES trip_allocations(allocation_id)
        ON DELETE CASCADE,

    FOREIGN KEY (forecast_id)
        REFERENCES harvest_forecasts(forecast_id)
        ON DELETE CASCADE
);

-- This table keeps track of payments made for trip allocations.

CREATE TABLE payments (
    payment_id      INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    allocation_id   INT           NOT NULL,
    farmer_id       INT           NOT NULL,
    payer_type      VARCHAR(50)   NOT NULL,
    payee_type      VARCHAR(50)   NOT NULL,
    payee_phone     VARCHAR(15)   NOT NULL,
    amount          NUMERIC(12,2) NOT NULL,
    currency        VARCHAR(3)    NOT NULL DEFAULT 'RWF',
    purpose         VARCHAR(100)  NOT NULL,
    status          VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    flutterwave_ref VARCHAR(100)  NULL UNIQUE,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    settled_at      TIMESTAMP     NULL,
    CONSTRAINT fk_payments_allocation
        FOREIGN KEY (allocation_id) REFERENCES trip_allocations(allocation_id) ON DELETE CASCADE,
    CONSTRAINT fk_payments_farmer
        FOREIGN KEY (farmer_id)     REFERENCES farmers(farmer_id)             ON DELETE CASCADE
);

-- Notifications table to keep track of messages sent to farmers and transporters.

CREATE TABLE notifications (
    notification_id INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_type  VARCHAR(50)   NOT NULL,   
    recipient_phone VARCHAR(15)   NOT NULL,
    channel         VARCHAR(50)   NOT NULL DEFAULT 'SMS',  
    message         TEXT          NOT NULL,
    status          VARCHAR(10)   NOT NULL DEFAULT 'QUEUED', 
    sent_time       TIMESTAMP     NULL,
    related_trip_id INT           NULL,
    CONSTRAINT fk_notif_trip
        FOREIGN KEY (related_trip_id) REFERENCES trip_allocations(allocation_id) ON DELETE SET NULL
);
-- API extensions

ALTER TABLE users
    ADD COLUMN email VARCHAR(120) NULL;

ALTER TABLE users
    ADD CONSTRAINT uq_users_email UNIQUE (email);

CREATE TABLE farmer_admin_profiles (
    farmer_id           INT          PRIMARY KEY,
    national_id         VARCHAR(20)  NULL UNIQUE,
    registration_status VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    registered_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_farmer_admin_profile
        FOREIGN KEY (farmer_id) REFERENCES farmers(farmer_id) ON DELETE CASCADE
);

CREATE TABLE truck_operational_details (
    truck_id           INT          PRIMARY KEY,
    vehicle_model      VARCHAR(100) NULL,
    driver_name        VARCHAR(100) NULL,
    current_location   VARCHAR(150) NULL,
    notes              VARCHAR(500) NULL,
    updated_by_user_id INT          NULL,
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_truck_details_truck
        FOREIGN KEY (truck_id) REFERENCES trucks(truck_id) ON DELETE CASCADE,
    CONSTRAINT fk_truck_details_user
        FOREIGN KEY (updated_by_user_id) REFERENCES users(user_id) ON DELETE SET NULL
);

CREATE TABLE cold_hub_accounts (
    hub_id  INT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    CONSTRAINT fk_cold_hub_account_hub
        FOREIGN KEY (hub_id) REFERENCES cold_hubs(hub_id) ON DELETE CASCADE,
    CONSTRAINT fk_cold_hub_account_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE cold_hub_capacity_updates (
    update_id             INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hub_id                INT          NOT NULL,
    updated_by_user_id    INT          NULL,
    total_capacity_kg     REAL         NOT NULL,
    available_capacity_kg REAL         NOT NULL,
    produce_type          VARCHAR(30)  NOT NULL DEFAULT 'tomatoes',
    notes                 VARCHAR(500) NULL,
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_hub_capacity_update_hub
        FOREIGN KEY (hub_id) REFERENCES cold_hubs(hub_id) ON DELETE CASCADE,
    CONSTRAINT fk_hub_capacity_update_user
        FOREIGN KEY (updated_by_user_id) REFERENCES users(user_id) ON DELETE SET NULL,
    CONSTRAINT chk_hub_capacity_update
        CHECK (available_capacity_kg >= 0 AND available_capacity_kg <= total_capacity_kg)
);

CREATE TABLE forecast_requirements (
    forecast_id     INT          PRIMARY KEY,
    needs_transport BOOLEAN      NOT NULL DEFAULT TRUE,
    needs_storage   BOOLEAN      NOT NULL DEFAULT TRUE,
    notes           VARCHAR(500) NULL,
    source          VARCHAR(10)  NOT NULL DEFAULT 'USSD',
    CONSTRAINT fk_forecast_requirements
        FOREIGN KEY (forecast_id) REFERENCES harvest_forecasts(forecast_id) ON DELETE CASCADE
);

CREATE TABLE hub_allocation_receipts (
    allocation_id        INT       PRIMARY KEY,
    confirmed_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_by_user_id INT       NULL,
    received_quantity_kg REAL      NOT NULL,
    CONSTRAINT fk_hub_receipt_allocation
        FOREIGN KEY (allocation_id) REFERENCES trip_allocations(allocation_id) ON DELETE CASCADE,
    CONSTRAINT fk_hub_receipt_user
        FOREIGN KEY (confirmed_by_user_id) REFERENCES users(user_id) ON DELETE SET NULL,
    CONSTRAINT chk_hub_receipt_quantity
        CHECK (received_quantity_kg > 0)
);

CREATE TABLE trip_status_events (
    event_id           INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    allocation_id      INT         NOT NULL,
    status             VARCHAR(10) NOT NULL,
    changed_by_user_id INT         NULL,
    created_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trip_status_event_allocation
        FOREIGN KEY (allocation_id) REFERENCES trip_allocations(allocation_id) ON DELETE CASCADE,
    CONSTRAINT fk_trip_status_event_user
        FOREIGN KEY (changed_by_user_id) REFERENCES users(user_id) ON DELETE SET NULL
);
