const $ = (selector, context = document) => context.querySelector(selector);
const $$ = (selector, context = document) => [...context.querySelectorAll(selector)];

function setText(selector, value) { const element = $(selector); if (element) element.textContent = value; }
function formatNumber(value) { return Number(value || 0).toLocaleString("en-US"); }
function formatDateTime(value) { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : date.toLocaleString("en-GB", { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" }); }
function showToast(message) { const toast = $("#toast"); if (!toast) return; toast.textContent = message; toast.classList.add("show"); window.setTimeout(() => toast.classList.remove("show"), 3200); }
function handleError(error, fallback) { if (error.status === 401) { window.location.assign(FreshLinkAPI.loginUrl); return; } showToast(error.message || fallback); }

function initTheme() { const button = $("#themeToggle"); if (!button) return; button.addEventListener("click", () => { const next = (document.documentElement.getAttribute("data-theme") || "light") === "light" ? "dark" : "light"; document.documentElement.setAttribute("data-theme", next); try { localStorage.setItem("freshlink-theme", next); } catch (error) {} }); }
function initGreeting() { const hour = new Date().getHours(); setText("#greeting", hour < 12 ? "Good morning" : hour < 18 ? "Good afternoon" : "Good evening"); setText("#todayDate", new Date().toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long", year: "numeric" })); }
function initSidebar() {
  const sidebar = $("#sidebar"); if (!sidebar) return; $("#sidebarCollapse")?.addEventListener("click", () => sidebar.classList.toggle("collapsed"));
  try { const width = localStorage.getItem("freshlink-sidebar-w"); if (width) document.documentElement.style.setProperty("--sb-w", `${width}px`); } catch (error) {}
  const handle = $("#resizeHandle"); if (handle) handle.addEventListener("mousedown", (event) => { if (sidebar.classList.contains("collapsed")) return; const resize = (move) => document.documentElement.style.setProperty("--sb-w", `${Math.max(200, Math.min(420, move.clientX))}px`); const stop = () => { const width = getComputedStyle(document.documentElement).getPropertyValue("--sb-w").trim().replace("px", ""); try { localStorage.setItem("freshlink-sidebar-w", width); } catch (error) {} window.removeEventListener("mousemove", resize); window.removeEventListener("mouseup", stop); }; event.preventDefault(); window.addEventListener("mousemove", resize); window.addEventListener("mouseup", stop); });
  const backdrop = document.createElement("div"); backdrop.className = "backdrop"; document.body.appendChild(backdrop); const close = () => { sidebar.classList.remove("open"); backdrop.classList.remove("show"); }; $("#menuToggle")?.addEventListener("click", () => { sidebar.classList.add("open"); backdrop.classList.add("show"); }); backdrop.addEventListener("click", close);
}
function updateGauge(available, total) { const gauge = $("#fleetGauge"); if (!gauge) return; const percentage = total ? Math.round(available / total * 100) : 0; const fill = $(".gauge-fill", gauge); const circumference = 2 * Math.PI * 52; fill.style.stroke = percentage <= 33 ? "#d64545" : percentage <= 66 ? "#d97706" : "#1f7a4d"; fill.style.strokeDashoffset = String(circumference - percentage / 100 * circumference); setText("#gaugePct", `${percentage}%`); setText("#gaugeAvail", formatNumber(available)); setText("#gaugeTotal", formatNumber(total)); }
function tableMessage(message) { const row = document.createElement("tr"), item = document.createElement("td"); item.colSpan = 6; item.className = "table-message"; item.textContent = message; row.appendChild(item); return row; }
function tripPill(status) { const value = String(status || "").toUpperCase(); const pill = document.createElement("span"); pill.className = `status-pill ${value === "SCHEDULED" ? "assigned" : value === "IN_PROGRESS" ? "active2" : "delivered"}`; pill.textContent = value === "IN_PROGRESS" ? "In progress" : value.charAt(0) + value.slice(1).toLowerCase(); return pill; }
function renderTrips(trips) { const body = $("#tripsBody"); if (!body) return; body.replaceChildren(); if (!trips.length) { body.appendChild(tableMessage("No trips have been assigned yet.")); return; } trips.forEach((trip) => { const row = document.createElement("tr"); const values = [`${trip.pickup_location.village || trip.pickup_location.sector} · ${formatDateTime(trip.pickup_start)}`, `${formatNumber(trip.total_load_kg)} kg`, trip.destination_hub.name, trip.truck.plate_number]; values.forEach((value) => { const cell = document.createElement("td"); cell.textContent = value; row.appendChild(cell); }); const status = document.createElement("td"); status.appendChild(tripPill(trip.status)); const action = document.createElement("td"); if (trip.status === "SCHEDULED" || trip.status === "IN_PROGRESS") { const button = document.createElement("button"); button.className = "btn btn-start"; button.dataset.action = trip.status === "SCHEDULED" ? "start" : "deliver"; button.dataset.allocationId = trip.allocation_id; button.textContent = trip.status === "SCHEDULED" ? "Start pickup" : "Mark delivered"; action.appendChild(button); } else action.textContent = "—"; row.append(status, action); body.appendChild(row); }); }
function truckState(status) { const value = String(status || "").toUpperCase(); if (value === "AVAILABLE") return { label: "Available", toggle: true }; if (value === "MAINTENANCE") return { label: "Maintenance", toggle: true }; return { label: "Busy", toggle: false }; }
function renderTrucks(trucks) { const list = $("#truckList"); if (!list) return; list.replaceChildren(); if (!trucks.length) { $("#truckEmpty").style.display = "block"; return; } $("#truckEmpty").style.display = "none"; trucks.forEach((truck) => { const state = truckState(truck.status); const row = document.createElement("div"); row.className = "truck-row"; const plate = document.createElement("span"); plate.className = "truck-plate"; plate.textContent = truck.plate_number; const meta = document.createElement("span"); meta.className = "truck-meta"; const model = document.createElement("b"); model.textContent = truck.vehicle_model || "Truck"; const capacity = document.createElement("span"); capacity.textContent = `Capacity ${formatNumber(truck.capacity_kg)} kg`; meta.append(model, capacity); const label = document.createElement("span"); label.className = `avail-state ${truck.status === "AVAILABLE" ? "on" : "off"}`; label.textContent = state.label; const toggle = document.createElement("button"); toggle.className = "avail-switch"; toggle.type = "button"; toggle.setAttribute("role", "switch"); toggle.setAttribute("aria-checked", String(truck.status === "AVAILABLE")); toggle.dataset.truckId = truck.truck_id; toggle.disabled = !state.toggle; toggle.title = state.toggle ? "Toggle availability" : "This truck cannot be changed while en route or full"; const knob = document.createElement("span"); knob.className = "knob"; toggle.appendChild(knob); row.append(plate, meta, label, toggle); list.appendChild(row); }); }
function setFleetStatus(available, total) { const tag = $("#fleet-status"); if (!tag) return; tag.replaceChildren(); const dot = document.createElement("span"); dot.className = available ? "dot ok" : "dot"; tag.append(dot, ` ${available} of ${total} trucks available`); }
async function loadDashboard() { try { const [dashboard, trips, trucks] = await Promise.all([FreshLinkAPI.request("/api/transporter/dashboard"), FreshLinkAPI.request("/api/transporter/trips?page_size=100"), FreshLinkAPI.request("/api/transporter/trucks")]); const profile = dashboard.transporter, fleet = dashboard.fleet, awaiting = dashboard.trips.awaiting_pickup || 0; setText("#transporter-heading", profile.name); setText("#sidebar-transporter-name", profile.name); setText("#assigned-trips-count", dashboard.trips.awaiting_pickup === null ? "—" : formatNumber(awaiting)); setText("#available-trucks-count", formatNumber(fleet.available_trucks)); setText("#total-trucks-count", `/ ${formatNumber(fleet.total_trucks)}`); setText("#available-capacity-count", formatNumber(fleet.available_capacity_kg)); setText("#delivered-today-count", formatNumber(dashboard.trips.delivered_today)); setText("#assignedNote", dashboard.coordination_data_available ? "awaiting pickup" : "engine trips unavailable"); setText("#navTripBadge", formatNumber(awaiting)); setText("#tripCount", dashboard.coordination_data_available ? `${awaiting} to pick up` : "No engine trips yet"); setText("#truckCount", `${fleet.total_trucks} truck${fleet.total_trucks === 1 ? "" : "s"}`); setText("#profile-name", profile.name); setText("#profile-sector", `${profile.base_sector}, ${profile.district}`); setText("#profile-fleet", `${fleet.total_trucks} trucks (${formatNumber(fleet.total_capacity_kg)} kg)`); setText("#profile-status", fleet.accepting_trips ? "Accepting trips" : "No trucks available"); setFleetStatus(fleet.available_trucks, fleet.total_trucks); updateGauge(fleet.available_trucks, fleet.total_trucks); renderTrips(trips.items); renderTrucks(trucks.items); } catch (error) { $("#tripsBody")?.replaceChildren(tableMessage("Unable to load trips.")); handleError(error, "Unable to load transporter data."); } }
function initTripActions() { $("#tripsTable")?.addEventListener("click", async (event) => { const button = event.target.closest("button[data-action]"); if (!button) return; button.disabled = true; try { await FreshLinkAPI.request(`/api/transporter/trips/${button.dataset.allocationId}/${button.dataset.action}`, { method: "POST" }); showToast(button.dataset.action === "start" ? "Pickup started." : "Trip marked delivered."); await loadDashboard(); } catch (error) { handleError(error, "Unable to update this trip."); button.disabled = false; } }); }
function initTruckToggles() { $("#truckList")?.addEventListener("click", async (event) => { const button = event.target.closest("button[data-truck-id]"); if (!button || button.disabled) return; const available = button.getAttribute("aria-checked") !== "true"; button.disabled = true; try { await FreshLinkAPI.request(`/api/transporter/trucks/${button.dataset.truckId}`, { method: "PATCH", body: JSON.stringify({ status: available ? "AVAILABLE" : "MAINTENANCE" }) }); showToast(`Truck marked ${available ? "available" : "under maintenance"}.`); await loadDashboard(); } catch (error) { handleError(error, "Unable to update truck availability."); button.disabled = false; } }); }
function initAddTruck() { const button = $("#addTruckBtn"); if (!button) return; button.addEventListener("click", async () => { const plate = $("#newPlate"), model = $("#newModel"), capacity = $("#newCapacity"); if (!plate.value.trim() || !capacity.value || Number(capacity.value) <= 0) { showToast("Enter a plate number and positive capacity."); return; } button.disabled = true; try { await FreshLinkAPI.request("/api/transporter/trucks", { method: "POST", body: JSON.stringify({ plate_number: plate.value, capacity_kg: Number(capacity.value), status: "AVAILABLE", vehicle_model: model.value.trim() || null }) }); plate.value = ""; model.value = ""; capacity.value = ""; showToast("Truck registered and marked available."); await loadDashboard(); } catch (error) { handleError(error, "Unable to register truck."); } finally { button.disabled = false; } }); }
document.addEventListener("DOMContentLoaded", () => { initTheme(); initGreeting(); initSidebar(); initTripActions(); initTruckToggles(); initAddTruck(); loadDashboard(); });
